apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: falco
  namespace: falco
spec:
  interval: 5m
  chart:
    spec:
      chart: falco
      version: '1.7.1'
      sourceRef:
        kind: HelmRepository
        name: falco
      interval: 1m
  values:
    ebpf:
      enabled: true
    falco:
      syscallEventDrops:
        actions: []
    customRules:
      rules-test.yaml: "" 
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: falcosidekick
  namespace: falco
spec:
  interval: 5m
  chart:
    spec:
      chart: falcosidekick
      version: '0.2.2'
      sourceRef:
        kind: HelmRepository
        name: falco
      interval: 1m
  values:
    customFields:
      fluxcd.io: cookies
---
apiVersion: source.toolkit.fluxcd.io/v1beta1
kind: HelmRepository
metadata:
  name: falco
  namespace: falco
spec:
  url: https://falcosecurity.github.io/charts/
  interval: 10m
