apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: falco
  namespace: falco
spec:
  interval: 5m
  chart:
    spec:
      chart: falco
      version: '1.7.1'
      sourceRef:
        kind: HelmRepository
        name: falco
      interval: 1m
  values:
    ebpf:
      enabled: true
    falco:
      syscallEventDrops:
        actions: []
    customRules:
      cookierules.yaml: |+
        - rule: Cookie recipes tampering detector
          desc: Detect tampering of super precious cookie recipes
          condition: modify
          output: Cookie recipes tampering detected, secure your cookies, make an espresso and eat all of them if necessary. No one can have them. (uid=%user.uid container_id=%container.id container_name=%container.name image=%container.image.repository:%container.image.tag %evt.arg.oldpath %evt.arg.path)
          priority: WARNING
          tags: [importantrecipesalert]

---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: falcosidekick
  namespace: falco
spec:
  interval: 5m
  chart:
    spec:
      chart: falcosidekick
      version: '0.2.2'
      sourceRef:
        kind: HelmRepository
        name: falco
      interval: 1m
  values:
    customFields:
      fluxcd.io: cookies
---
apiVersion: source.toolkit.fluxcd.io/v1beta1
kind: HelmRepository
metadata:
  name: falco
  namespace: falco
spec:
  url: https://falcosecurity.github.io/charts/
  interval: 10m
