apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: falco
  namespace: falco
spec:
  interval: 5m
  chart:
    spec:
      chart: falco
      sourceRef:
        kind: HelmRepository
        name: falco
      interval: 1m
  values:
    falcosidekick:
      enabled: true
      webui:
         enabled: true
    fakeEventGenerator:
      enabled: false
    ebpf:
      enabled: true
    customRules:
      cookierules.yaml: |+
        - rule: GITOPS DAY 2021
          desc: Detect tampering of cookie recipes
          condition: ((evt.type=open or evt.type=openat) and fd.name startswith '/usr/share/nginx') or (modify and evt.arg.oldpath startswith '/usr/share/nginx') or (modify and evt.arg.path startswith '/usr/share/nginx') or (modify and fd.name startswith '/usr/share/nginx') or (modify and evt.arg.name startswith '/usr/share/nginx')
          output: Cookie recipes tampering detected, secure your cookies. (uid=%user.uid container_id=%container.id container_name=%container.name image=%container.image.repository:%container.image.tag oldpath=%evt.arg.oldpath path=%evt.arg.path fd.name=%fd.name name=%evt.arg.name)
          priority: EMERGENCY
          tags: [importantrecipesalert]
      cookienginx-network.yaml: |-    
        - rule: Unauthorized process opened an outbound connection (nginx)
          desc: A nginx process tried to open an outbound connection and is not whitelisted
          condition: outbound and evt.rawres >= 0 and app_nginx
          output: Non-whitelisted process opened an outbound connection (command=%proc.cmdline connection=%fd.name)
          priority: WARNING
---
apiVersion: source.toolkit.fluxcd.io/v1beta1
kind: HelmRepository
metadata:
  name: falco
  namespace: falco
spec:
  url: https://falcosecurity.github.io/charts/
  interval: 10m
