---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta1
kind: Kustomization
metadata:
  name: kubeless
  namespace: kubeless
spec:
  interval: 2m0s
  path: ./lib/kubeless
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  validation: client
  healthChecks:
    - kind: Deployment
      name: kubeless-controller-manager
      namespace: kubeless
